### PR TITLE
Replace deprecated HttpModule from @nestjs/common with @nestjs/axios

### PR DESCRIPTION
**Pull request by keks42**
As the new axios HttpModules respects the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY, there is no need to configure it explicitly anymore. 

This fixes issue #390

### CODE REVIEW

**Review by trikona — APPROVED** [review]

**Comment by ugrave** [comment]
Any plans to merge this PR?

**Comment by keks42** [comment]
@wing328 @kay-schecker 
As you merged the last PRs in this repo - do you know who might be able to review this PR and decide if it can be merged?

**Review by feoware — APPROVED** [review]

**Comment by rishabh1212** [comment]
@feodorar when can this PR be merged?

**Comment by feodorar** [comment]
@rishabh1212 That is out of my hands, I'm afraid. I just did a peer review...

**Comment by wing328** [comment]
Sorry for the delay in reviewing this change.

Please take a look at the build errors. 

Not sure if it's related to https://github.com/OpenAPITools/openapi-generator-cli/pull/651/commits/49b383b705d3c7d87449387ef439f3add5eba058.

Once resolved, I'll try to handle it with higher priority.

**Comment by wing328** [comment]
> <div data-turbo-body="" class="logged-in env-production page-responsive full-width full-width-p-0" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; overflow-wrap: break-word;"><div class="application-main " data-commit-hovercards-enabled="" data-discussion-hovercards-enabled="" data-issue-and-pr-hovercards-enabled="" style="box-sizing: border-box;"><div itemscope="" itemtype="http://schema.org/SoftwareSourceCode" class="" style="box-sizing: border-box;"><main style="box-sizing: border-box; display: block;"><run-summary data-catalyst="" style="box-sizing: border-box; display: block;"><turbo-frame id="repo-content-turbo-frame" target="_top" data-turbo-action="advance" class="" style="box-sizing: border-box; display: block;"><div class="repository-content " style="box-sizing: border-box; width: 1905px;"><div class="clearfix new-discussion-timeline container-xl px-3 px-md-4 px-lg-5" style="box-sizing: border-box; max-width: none; margin-right: auto; margin-left: auto; padding: 0px !important; width: 1905px;"><split-page-layout data-view-component="true" class="PageLayout PageLayout--columnGap-none PageLayout--rowGap-none PageLayout--responsive-separateRegions PageLayout--innerSpacing-normal PageLayout--responsive-primary-content PageLayout--panePos-start PageLayout--paneWidth-wide PageLayout--hasPaneDivider" data-catalyst="" style="box-sizing: border-box; display: block; margin: var(--Layout-outer-spacing-y) var(--Layout-outer-spacing-x); --Layout-pane-width: 336px; --Layout-inner-spacing-min: 16px; --Layout-inner-spacing-max: 24px; --Layout-column-gap: 0px; --Layout-row-gap: 0px; --Layout-template-columns: var(--Layout-pane-width) minmax(0, calc(100% - var(--Layout-pane-width) - var(--Layout-column-gap))); --Layout-template-areas: &quot;pane content&quot;;"><div data-view-component="true" class="PageLayout-wrapper" style="box-sizing: border-box; display: grid; grid: auto-flow auto / 1fr; row-gap: var(--Layout-row-gap);"><div data-view-component="true" class="PageLayout-columns" style="box-sizing: border-box; display: grid; column-gap: var(--Layout-column-gap); row-gap: var(--Layout-row-gap); grid-template-columns: var(--Layout-template-columns); grid-template-rows: 1fr; grid-template-areas: var(--Layout-template-areas);"><div data-target="split-page-layout.content" data-view-component="true" class="PageLayout-region PageLayout-content" style="box-sizing: border-box; padding-top: ; padding-right: var(--Layout-inner-spacing-max); padding-bottom: ; padding-left: var(--Layout-inner-spacing-max); grid-area: content / content / content / content; max-width: 100vw;"><div class="flex-auto pb-5" style="box-sizing: border-box; flex: 1 1 auto !important; padding-bottom: var(--base-size-32, 32px)  !important;"><div class="js-updatable-content js-socket-channel" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjk2OTk3NzUzNzQiLCJ0IjoxNjcwMzQyMDg1fQ==--77ba4f4e6a97591327994d26a4b9a9d4934cb632028f339fc46ca15f862525c2" data-url="/OpenAPITools/openapi-generator-cli/actions/runs/3630986600/annotations_partial" style="box-sizing: border-box;"><div class="actions-fullwidth-module color-bg-default color-shadow-small mb-3 pt-3 pb-1 border rounded" style="box-sizing: border-box; border: var(--primer-borderWidth-thin, 1px) solid var(--color-border-default)  !important; border-radius: var(--primer-borderRadius-medium, 6px)  !important; box-shadow: var(--color-shadow-small)  !important; background-color: var(--color-canvas-default)  !important; margin-bottom: var(--base-size-16, 16px)  !important; padding-bottom: var(--base-size-4, 4px)  !important; padding-top: var(--base-size-16, 16px)  !important;">

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2Show less
--


</div></div><div id="artifacts" class="js-updatable-content js-socket-channel" data-channel="eyJjIjoid29ya2Zsb3dfcnVuOjM2MzA5ODY2MDA6ZXhlY3V0aW9uIiwidCI6MTY3MDM0MjA4NX0=--8faee144fd33c3c45e36060f3b6f3698019bd048619911397532bb1b5a14424a eyJjIjoid29ya2Zsb3dfcnVuOjM2MzA5ODY2MDA6YXJ0aWZhY3RzIiwidCI6MTY3MDM0MjA4NX0=--862c776ab935986b69ede807c8a6bd99f5e3884db358eb20df77a862fcfa78c3" data-url="/OpenAPITools/openapi-generator-cli/actions/runs/3630986600/artifacts_partial" style="box-sizing: border-box;"></div><job-summaries class="js-updatable-content js-socket-channel" data-retain-focus="" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjk2OTk3NzUzNzQiLCJ0IjoxNjcwMzQyMDg1fQ==--77ba4f4e6a97591327994d26a4b9a9d4934cb632028f339fc46ca15f862525c2" data-url="/OpenAPITools/openapi-generator-cli/actions/runs/3630986600/job_summary_partial" data-catalyst="" style="box-sizing: border-box; display: block;"><svg aria-hidden="true" width="320px" height="84px" viewBox="0 0 340 84" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="diff-placeholder-svg position-absolute bottom-0"><defs><clipPath id="diff-placeholder"><rect x="0" y="0" width="67.0175439" height="11.9298746" rx="2"></rect><rect x="18.9473684" y="47.7194983" width="100.701754" height="11.9298746" rx="2"></rect><rect x="0" y="71.930126" width="37.8947368" height="11.9298746" rx="2"></rect><rect x="127.017544" y="48.0703769" width="53.3333333" height="11.9298746" rx="2"></rect><rect x="187.719298" y="48.0703769" width="72.9824561" height="11.9298746" rx="2"></rect><rect x="76.8421053" y="0" width="140.350877" height="11.9298746" rx="2"></rect><rect x="17.8947368" y="23.8597491" width="140.350877" height="11.9298746" rx="2"></rect><rect x="166.315789" y="23.8597491" width="173.684211" height="11.9298746" rx="2"></rect></clipPath><linearGradient id="animated-diff-gradient" x1="0" x2="0" y1="0" y2="1" spreadMethod="reflect"></linearGradient></defs></svg></job-summaries></div></div></div></div></split-page-layout><div class="js-updatable-content js-socket-channel" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjk2OTk3NzUzNzQiLCJ0IjoxNjcwMzQyMDg1fQ==--77ba4f4e6a97591327994d26a4b9a9d4934cb632028f339fc46ca15f862525c2" data-url="/OpenAPITools/openapi-generator-cli/actions/runs/3630986600/job_rerun_dialogs_partial" style="box-sizing: border-box;"><div class="js-updatable-content js-socket-channel" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjk2OTk3NzUzNzQiLCJ0IjoxNjcwMzQyMDg2fQ==--0198e2f224ae753d1b173338c6492f45123a898ee20a8d3b70007d611a048348" data-url="/OpenAPITools/openapi-generator-cli/actions/runs/3630986600/job_rerun_dialogs_partial" style="box-sizing: border-box;"></div></div></div></div></turbo-frame></run-summary></main></div></div></div><br class="Apple-interchange-newline">


I think that's probably the reason.

Please update the github workflow accordingly as part of this PR. Thank you.

**Comment by keks42** [comment]
@wing328 
Thank you so much for the review (& for already merging the master for me)

The problem with the failing pipeline was me not having executed yarn install properly which made "yarn --frozen-lock" fail because of differences in the yarn.lock-file. Now that I did that properly and fixed the yarn.lock-file it should be successful. 

Although the node version should not have been a problem, I looked into it. I upgraded all github actions and it looks like you use a matrix build strategy but did not define the values to be used for the node-version. I added the node version 16.x which should use version 16 with the latest minor and patch version. So in the future it can be assured to run with multiple versions.

Seems as if there is an approval needed for the pipeline to run, so let's see if it is successful now.

**Comment by rishabh1212** [comment]
@wing328 @keks42 it is still awaiting approval from some reviewer who has the write access.

**Review by wing328 — APPROVED** [review]

**Comment by keks42** [comment]
@wing328 What is missing now for all the checks to complete? I do not understand the last thing that is still expected :/

**Comment by wing328** [comment]
No idea why the last step stuck at build state.

I've gone ahead to merge it. Let's see how that goes.

Thanks again for the PR.

**Pull request merged**
