### PR TITLE
support JAVA_HOME environment variable

### LINKED ISSUE #661: [BUG] cli doesn't support JAVA_HOME, requires the java executable to be on the PATH
# 🐛 Bug Report:

### Describe the bug
When running `openapi-generator-cli` via NPM script:
`Error: 'java' is not recognized as an internal or external command, operable program or batch file.`

### Steps to Reproduce

Have a clean operating system, with no Java installation.

"Install" the JDK by downloading and then unzipping the portable [zip archive](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip), then set `JAVA_HOME` to that location.
 

### Expected behavior

Like all other tooling in the Java ecosystem, openapi-generator-cli should try to execute the JDK via `$JAVA_HOME/bin/java` before falling back to looking for the java executable on the path. 

### Operation System (please complete the following information):
 - OS: Windows (problem exists on any other OS too)
 - Version 2.5.1

### Package System (please complete the following information):
 - whatever NPM comes by default with Node.js 16.17.0

### Additional context

This is a problem for developers working in more complex environments where they might need to work on multiple separate projects that require different JDK versions.  It's not viable to always be swapping the global path between different JDK installations.

This is actually a thing in the Node ecosystem too, you can (and people do) install and run Node via a [portable archive](https://nodejs.org/dist/v16.17.0/node-v16.17.0-win-x64.zip), without adding the node / npm executables to the global path.

If `JAVA_HOME` support is added, the readme should be updated to reflect that users don't necessarily need to have `java` on their `PATH` any more.

### PR DESCRIPTION
**Pull request by adnbrownie**
fixes  #661

### CODE REVIEW

**Comment by wing328** [comment]
Is the path to the `java` command correctly set in the `PATH` environment variable in your setup?

If it's, I don't think we need to use JAVA_HOME in the code base as suggested by this PR.

**Comment by adnbrownie** [comment]
As mentioned in https://github.com/OpenAPITools/openapi-generator-cli/issues/661, it is a common practice in the Java world to go for the `JAVA_HOME` environment variable. The main reason is that you might need different versions of the JDK for different Java projects, so referring to a global Java installation through the PATH variable might not always suit the needs of the various projects. In the JS world, tools like `nvm` (Node Version Manager) were introduced for the same purpose.

**Comment by adnbrownie** [comment]
I don't have time immediately, but I can look into the failing tests at some point.

**Comment by mok-liee** [comment]
i think it would be nicer to use `JAVA_HOME` or better to configure the java runtime via the `openapitools.json`.

sometimes there is a JRE/JDK given in the `PATH` envs from the system, maybe controlled by administrators.
overriding this in the user envs would not help.

**Comment by wing328** [comment]
@mok-liee can you please file a new PR based on this one and resolve the merge conflicts?

**Comment by wing328** [comment]
thanks for the PR.

closed via https://github.com/OpenAPITools/openapi-generator-cli/pull/756 instead

**Pull request closed without merging**
