### PR TITLE
chore(deps): update dependencies and fixing vulnerabilities

### PR DESCRIPTION
**Pull request by elmarbeckmann**
Hi @wing328! As requested in https://github.com/OpenAPITools/openapi-generator-cli/pull/722, here is my PR. I have no clue if I did this the correct way because I've actually never done a PR from a fork before. 

Anyways, I've updated to the latest version of NX, but it wasn't as easy as I expected. In fact, I had to refactor a lot to make it all work. Also a lot of other dependencies needed to be updated and there were some issues with for example Jest. I also had to refactor some configuration files for webpack, jest and nx to make those work together. 

Also fixed many many many severe vulnerabilities by doing some audit stuff. 

Tests, linting and building is successful. I haven't tested if the tool itself is running fine still. anyways, not sure where to go from here, please advise.

fix https://github.com/OpenAPITools/openapi-generator-cli/issues/719

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. approved the workflow. let's see how that goes

**Comment by wing328** [comment]
thanks for the PR and the tests passed.

let's give it a try

**Comment by wing328** [comment]
released via https://github.com/OpenAPITools/openapi-generator-cli/commit/7cc735e8e2cd1e47beae51b292815c117f03592b

i did a test and it works as expected👍

**Comment by elmarbeckmann** [comment]
Awesome

**Comment by rtmingo** [comment]
Thank you so much for this!

**Pull request merged**
