### PR TITLE
Fix @nestjs/axios version

### PR DESCRIPTION
**Pull request by daniel-shuy**
`@nestjs/axios` `0.0.8` has a peer dependency on `@nestjs/common` `^7.0.0 || ^8.0.0` (https://github.com/nestjs/axios/blob/0.0.8/package.json#L49), but ` @openapitools/openapi-generator-cli` depends on `@nestjs/common` `9.3.11`, which fails strict peer dependency checks (e.g. NPM's [--strict-peer-deps](https://docs.npmjs.com/cli/v7/using-npm/config#strict-peer-deps) or PNPM's [strict-peer-dependencies](https://pnpm.io/npmrc#strict-peer-dependencies)).

`@nestjs/axios` `0.1+` supports `@nestjs/common` `^9.0.0` (https://github.com/nestjs/axios/blob/0.1.0/package.json#L49).

`3.0.0` is the latest version of `@nestjs/axios` that still supports `@nestjs/common` `9.3.11`, and meets all the other peer dependencies (https://github.com/nestjs/axios/blob/3.0.0/package.json#L48).

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR but the CI failed: https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/5529892048/jobs/10115444160?pr=710

can you please take a look when you've time?

**Comment by daniel-shuy** [comment]
Oops sorry I editing the `package.json` using the GitHub web editor, but I forgot I needed to run `yarn install` to update the `yarn.lock` file. I've rerun `yarn install` with the same version of `yarn` used by the GitHub Actions (`1.22.19`)

**Comment by wing328** [comment]
that's ok. thanks again for the PR.

but the build failed: https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/5550379469/jobs/10138303847?pr=710

can you please take a look when you've time?

**Comment by wing328** [comment]
thanks for the PR. let's give it a try

**Pull request merged**
