### PR TITLE
support JAVA_HOME environment variable

### LINKED ISSUE #661: [BUG] cli doesn't support JAVA_HOME, requires the java executable to be on the PATH
# 🐛 Bug Report:

### Describe the bug
When running `openapi-generator-cli` via NPM script:
`Error: 'java' is not recognized as an internal or external command, operable program or batch file.`

### Steps to Reproduce

Have a clean operating system, with no Java installation.

"Install" the JDK by downloading and then unzipping the portable [zip archive](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip), then set `JAVA_HOME` to that location.
 

### Expected behavior

Like all other tooling in the Java ecosystem, openapi-generator-cli should try to execute the JDK via `$JAVA_HOME/bin/java` before falling back to looking for the java executable on the path. 

### Operation System (please complete the following information):
 - OS: Windows (problem exists on any other OS too)
 - Version 2.5.1

### Package System (please complete the following information):
 - whatever NPM comes by default with Node.js 16.17.0

### Additional context

This is a problem for developers working in more complex environments where they might need to work on multiple separate projects that require different JDK versions.  It's not viable to always be swapping the global path between different JDK installations.

This is actually a thing in the Node ecosystem too, you can (and people do) install and run Node via a [portable archive](https://nodejs.org/dist/v16.17.0/node-v16.17.0-win-x64.zip), without adding the node / npm executables to the global path.

If `JAVA_HOME` support is added, the readme should be updated to reflect that users don't necessarily need to have `java` on their `PATH` any more.

### PR DESCRIPTION
**Pull request by mok-liee**
fixes  #661

### CODE REVIEW

**Comment by mok-liee** [comment]
is it possible to run a test locally? i am working on windows with the git-bash.
if i run the unit-test it fails on all because of wrong interpretation of path's slash direction.

image

i want to get rid of this errors to see exactly whether adjustments to the unit-test are necessary.
i suspect that the modification brings this with it.

**Comment by mok-liee** [comment]
it looks to me like i can't do anything about the build problem, can i? a manual generate with the versions that throw errors in the log works locally for me.

**Comment by wing328** [comment]
> it looks to me like i can't do anything about the build problem, can i? 

one way is to repeat the issue in your fork.

**Comment by mok-liee** [comment]
I am completly new to Github actions. I will do my best.

**Comment by mok-liee** [comment]
sorry for messing up this PR but i dont know how to test this build locally. i thought if i do this in my fork this PR is free of my debuggings.

i see that the agent is using `/usr/lib/jvm/temurin-11-jdk-amd64` from `$JAVA_HOME` but the logs are printing out that the executable is not found. i try to figure out more.

**Comment by mok-liee** [comment]
this build should be successful

**Comment by wing328** [comment]
@mok-liee thanks. all tests passed.

one more minor request:

can you please update the workflow file to run the build on `windows-latest` as well?

ref: https://stackoverflow.com/a/64036382/677735

**Comment by mok-liee** [comment]
i will implement this. unfortunately, the weekend will be difficult. i will try next week!

**Comment by wing328** [comment]
I tried but looks like it will be very difficult as the tests won't work on both windows and linux: https://github.com/OpenAPITools/openapi-generator-cli/pull/757

e.g.
```
Object {
        "after": Array [
    -     "Downloaded 4.2.0 to custom storage location /c/w/d/custom/dir",
    +     "Downloaded 4.2.0 to custom storage location D:\\c\\w\\d\\custom\\dir",
        ],
        "before": Array [
          "Download 4.2.0 ...",
        ],
      }

      4[43](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:44) |               await compile();
      [44](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:45)4 |               await fixture.download('4.2.0');
    > 4[45](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:46) |               expect(logMessages).toEqual({
          |                                   ^
      4[46](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:47) |                 before: [chalk.yellow(`Download 4.2.0 ...`)],
      4[47](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:48) |                 after: [
      4[48](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:49) |                   chalk.green(

      at src/app/services/version-manager.service.spec.ts:445:35
      at fulfilled (../../node_modules/tslib/tslib.js:166:[62](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:63))

  ● VersionManagerService › API › download() › the server responds a file › logging › there is a custom storage location › returns /custom/dir for /custom/dir

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "after": Array [
    -     "Downloaded 4.2.0 to custom storage location /custom/dir",
    +     "Downloaded 4.2.0 to custom storage location D:\\custom\\dir",
        ],
        "before": Array [
          "Download 4.2.0 ...",
        ],
      }

      443 |               await compile();
      444 |               await fixture.download('4.2.0');
    > 445 |               expect(logMessages).toEqual({
          |                                   ^
      446 |                 before: [chalk.yellow(`Download 4.2.0 ...`)],
      447 |                 after: [
      448 |                   chalk.green(

      at src/app/services/version-manager.service.spec.ts:445:35
      at fulfilled (../../node_modules/tslib/tslib.js:1[66](https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/8128392726/job/22214232230?pr=757#step:6:67):62)
```

**Comment by wing328** [comment]
we will get this merged and find another way to test it on windows later with another PR instead

**Pull request merged**
